### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by DakPro** [SashaT9/CPv2#3]
create table solutions (
    solution_id serial primary key,
    answer text not null
);
create table submissions (
    user_id int references users(user_id),
    problem_id int references problems(problem_id),
    solution_id int references solutions(solution_id),
    status text,
    primary key (user_id, problem_id, solution_id)
);

What is table 'solution' that we need to include it in 'submissions' table?

**Comment by SashaT9** [comment]
for handling 'update problem'

**Comment by DakPro** [comment]
Solution in this table means the correct solution of the problem given by the authors or CODE written by submitter or OUTPUT of submitter?
